### ISSUE TITLE
graphics question

### ISSUE THREAD

**Issue by davephillips** [rorywalsh/CabbageRack#1]
Hey Rory, is this how the UI is supposed to appear ? Please advise if I'm missing something. Very cool project !! Rack 0.5.x, btw.

![cabbagerackexampleui](https://user-images.githubusercontent.com/7815938/36737149-61535f02-1ba8-11e8-913a-0028b2c1ba11.png)

**Comment by rorywalsh** [comment]
I literally emailed you about 10 seconds before this came in! Can you try to pull again, I just updated the example and the readme.

**Comment by davephillips** [comment]
Yeh, I got your mail right after posting. :) You bet, I'll check out the lates & greatest, will report back asap.

**Comment by davephillips** [comment]
Okay, here's what I get now. The example illustrates a minor (?) problem: Once the controls have been turned they don't return to their original zero position (i.e. full left). Also, it looks like the module size is a bit off (see the gap between your module and the ADSR). Otherwise the example appears to work as advertised. :)
![cabbagerackexampletest](https://user-images.githubusercontent.com/7815938/36743291-ea31559a-1bb7-11e8-958a-6bc1ee8aa592.png)

**Comment by rorywalsh** [comment]
What about the audio Dave, is it running ok for you? I had to increase my
ksmps size to improve things in my old laptop. The GUI should be easy to
fix.

**Comment by davephillips** [comment]
Audio is fine so far.

**Comment by rorywalsh** [comment]
I just pushed a fix for this, we just needed to change the width of the form to 150. The example provided is really just a minimal test of CV ins/out and some control parameters. I will try to put together some more meaningful examples when I get a bit further down the road with it.
