### ISSUE TITLE
error building on Linux Fedora

### ISSUE THREAD

**Issue by poulpoulsen** [rorywalsh/CabbageRack#14]
hello,
i just try to compile CabbageRack with the latest Rack-SDK as described here.
compiling starts, but breaks with the following error.
Any idea?

`
g++ -I /usr/include/csound -std=c++11 -Wsuggest-override  -fPIC -I/home/held/src/Rack-SDK/include -I/home/held/src/Rack-SDK/dep/include -fno-gnu-unique -MMD -MP -g -O3 -march=nehalem -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -c -o build/src/CabbageRackWidget.cpp.o src/CabbageRackWidget.cpp
In Datei, eingebunden von src/CabbageRackWidget.cpp:3:
src/CabbageWidgets.hpp: In Konstruktor »CabbageRotarySlider::CabbageRotarySlider(CabbageControl, rack::engine::Module*, int)«:
src/CabbageWidgets.hpp:91:25: Fehler: »paramQuantity« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »getParamQuantity«?
   91 |                         paramQuantity = mod->paramQuantities[id];
      |                         ^~~~~~~~~~~~~
      |                         getParamQuantity
src/CabbageWidgets.hpp:109:32: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »minValue«?
  109 |                 currentValue = dirtyValue;
      |                                ^~~~~~~~~~
      |                                minValue
src/CabbageWidgets.hpp: In Elementfunktion »virtual void CabbageRotarySlider::draw(const rack::widget::Widget::DrawArgs&)«:
src/CabbageWidgets.hpp:132:44: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »minValue«?
  132 |                 const float sliderValue = (dirtyValue+abs(min))/(abs(maxValue));
      |                                            ^~~~~~~~~~
      |                                            minValue
src/CabbageWidgets.hpp: In Konstruktor »CabbageButton::CabbageButton(CabbageControl, rack::engine::Module*, int)«:
src/CabbageWidgets.hpp:213:25: Fehler: »paramQuantity« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »getParamQuantity«?
  213 |                         paramQuantity = mod->paramQuantities[id];
      |                         ^~~~~~~~~~~~~
      |                         getParamQuantity
src/CabbageWidgets.hpp: In Elementfunktion »virtual void CabbageButton::draw(const rack::widget::Widget::DrawArgs&)«:
src/CabbageWidgets.hpp:256:21: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht definiert
  256 |                 if (dirtyValue==0)
      |                     ^~~~~~~~~~
src/CabbageWidgets.hpp:268:131: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht definiert
  268 | 2)-(11.f/2.f)-int(value), FramebufferWidget::box.size.x-int(dirtyValue), text[int(dirtyValue)].c_str(), NULL);
      |                                                             ^~~~~~~~~~

src/CabbageWidgets.hpp: In Konstruktor »CabbageCombobox::CabbageCombobox(CabbageControl, rack::engine::Module*, int)«:
src/CabbageWidgets.hpp:286:25: Fehler: »paramQuantity« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »getParamQuantity«?
  286 |                         paramQuantity = mod->paramQuantities[id];
      |                         ^~~~~~~~~~~~~
      |                         getParamQuantity
src/CabbageWidgets.hpp:294:17: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht definiert
  294 |                 dirtyValue = control.value;
      |                 ^~~~~~~~~~
src/CabbageWidgets.hpp: In Elementfunktion »virtual void CabbageCombobox::draw(const rack::widget::Widget::DrawArgs&)«:
src/CabbageWidgets.hpp:324:89: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht definiert
  324 | rgs.vg, 0, (box.size.y/2)-(11.f/2.f), box.size.x, text[(int(dirtyValue-1) < 0 ? 0 : int(dirtyValue-1))].c_str(), NULL);
      |                                                             ^~~~~~~~~~

src/CabbageWidgets.hpp: In Konstruktor »CabbageCheckbox::CabbageCheckbox(CabbageControl, rack::engine::Module*, int)«:
src/CabbageWidgets.hpp:342:25: Fehler: »paramQuantity« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »getParamQuantity«?
  342 |                         paramQuantity = mod->paramQuantities[id];
      |                         ^~~~~~~~~~~~~
      |                         getParamQuantity
src/CabbageWidgets.hpp: In Elementfunktion »virtual void CabbageCheckbox::draw(const rack::widget::Widget::DrawArgs&)«:
src/CabbageWidgets.hpp:370:21: Fehler: »dirtyValue« wurde in diesem Gültigkeitsbereich nicht definiert
  370 |                 if (dirtyValue==0)
      |                     ^~~~~~~~~~
make: *** [/home/held/src/Rack-SDK/compile.mk:72: build/src/CabbageRackWidget.cpp.o] Fehler 1
`

**Comment by rorywalsh** [comment]
It's probably due to changes in the rack-sdk. Every new update seems to
bring more changes. Tbh, I'm losing interest in maintaining this. It gets
very frustrating.

**Comment by poulpoulsen** [comment]
oh i see. that is frustrating indeed.
perhaps i could use an older sdk.
do you know, which one you tested?

**Comment by rorywalsh** [comment]
According to the latest release(https://github.com/rorywalsh/CabbageRack/releases) rack-sdk 1.0, I guess that's already quite old.

**Comment by poulpoulsen** [comment]
ok, only with this version it is compiling. i tried 1.1.6 and does not work.
but unfortunately the building of cabbage with this cabbagerack build directory does not work.
the build script from cabbage is not finding this directory, tries to download and fails.
where should i place the directory of cabbagerack?

**Comment by poulpoulsen** [comment]
hello,
i just give it a new try.
and now with the newest version from git the compilation and running works out of the Box.
Thank you for your hard work!

Regards
Poul
