### ISSUE TITLE
[question] any chance to update it for Rack2?

### ISSUE THREAD

**Issue by poulpoulsen** [rorywalsh/CabbageRack#15]
hello,
i tried to run it inside Rack2, but the build of CabbageRack is only for V1.
any plan to update it for V2 of Rack?

Regards
Poul

**Comment by rorywalsh** [comment]
I'm not sure I'll get around to this anytime soon. Do you have any programming experience? You might have a go at updating yourself, I'd be happy to help? In the meantime, if you want to use Csound in VCV Rack 2 you can try [dbRackCsound](https://github.com/docb/dbRackCsound). Looks like a nice interface. Simple, yet powerful.

**Comment by poulpoulsen** [comment]
Wow thank you for this info.
i will check it.
