### ISSUE TITLE
Necessary to call `make install` after `make`?

### ISSUE THREAD

**Issue by brylie** [rorywalsh/CabbageRack#4]
After running `make`, how do we install CabbageRack in a location where Cabbage can find it? E.g. we would typically run `make install`, which produces the following output:

```sh
$ make install
rm -rf dist
mkdir -p dist/"CabbageRack"
cp plugin.so dist/"CabbageRack"/
strip -s dist/"CabbageRack"/plugin.so
cp -r --parents LICENSE.txt res README.md plugin.json dist/"CabbageRack"/
cd dist && zip -q -9 -r "CabbageRack"-"1.0.0"-lin.zip "CabbageRack"
cp dist/"CabbageRack"-"1.0.0"-lin.zip /home/bco/.Rack/plugins-v1/
```

Related to https://github.com/rorywalsh/cabbage/issues/125

**Comment by rorywalsh** [comment]
I think this can be closed now considering the new make system will install it into the correct location for Cabbage.
